apiVersion: apps/v1
kind: Deployment
metadata:
  name: dino
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dino
  template:
    metadata:
      labels:
        app: dino
    spec:
      containers:
      - name: nlp-app
        image: gcr.io/k8s-sent-deployment/myapp:v1
        ports:
        - containerPort: 5000
