name: ci dino-pygame
on: [push]
jobs:
  check-pygame:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6' 
        architecture: 'x64' 
    - run: |
        python -m pip install --upgrade pip
        python3 -m pip install pygame==2.0.0.dev12
